# Generated by Django 4.2.3 on 2023-08-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_genre_color"),
    ]

    operations = [
        migrations.AddField(
            model_name="moviecomment",
            name="is_spoiler",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
